twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig'] # accepte plusieurs thèmes
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
