version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  www:
    build: ./docker/php/
    container_name: container_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

  database:
    image: mysql
    container_name: container_database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: container_phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
    networks:
      - dev

networks:
  dev:
    # volumes:
    #   - db-data:/var/lib/postgresql/data:rw
    # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
    # - ./docker/db/data:/var/lib/postgresql/data:rw
    ###< doctrine/doctrine-bundle ###

volumes:
  db-data: ###< doctrine/doctrine-bundle ###
